# Generated by Django 4.1.7 on 2023-04-01 22:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified date')),
                ('deleted', models.DateTimeField(null=True, verbose_name='deleted date')),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
